### ISSUE TITLE
BUG: ANS event scraper fails 

### ISSUE THREAD

**Issue by csmcallister** [DataKind-DC/capital-nature-ingest#136]
## Expected Behavior
Scraper works without a hitch!

## Current Behavior
```bash
2019-06-25 18:39:45,913 - __main__ - CRITICAL - Exception getting events in events.ans:  max() arg is an empty sequence
Traceback (most recent call last):
  File "/Users/mcallistercs/Desktop/Github/capital-nature-ingest/events/ans.py", line 38, in get_event_description
    p_tags = eventon_full_description.find_all('p')
AttributeError: 'NoneType' object has no attribute 'find_all'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "get_events.py", line 101, in get_events
    source_events = event_source.main()
  File "/Users/mcallistercs/Desktop/Github/capital-nature-ingest/events/ans.py", line 92, in main
    event_description = get_event_description(event_website_soup)
  File "/Users/mcallistercs/Desktop/Github/capital-nature-ingest/events/ans.py", line 43, in get_event_description
    event_description = max([p.get_text() for p in p_tags], key = len)
ValueError: max() arg is an empty sequence
```

## Possible Solution
This is cause by the ANS event page no longer having a div tag with the `eventon_desc_in` class. Add a logging function to the offending line (`eventon_full_description = event_website_soup.find('div', {'class':'eventon_desc_in'})`) to log the event website url in the case of a failure and then inspect the page to see how to better scrape.

## Context
This bug was caught in `__main__`, so it broke the entire ANS scraper. Fixing this is a priority.

**Comment by csmcallister** [comment]
closed by 284c384
