### ISSUE TITLE
BUG: Event sources can display event datetimes in a variety of formats.

### ISSUE THREAD

**Issue by csmcallister** [DataKind-DC/capital-nature-ingest#144]
## Expected Behavior
Event sources can display event datetimes in a variety of formats. We log errors when something unexpected is encountered so that we can make a patch.

## Current Behavior
There are a few Montgomery County events that raise warnings:

```bash
2019-07-30 18:27:42,887 - events.montgomery - WARNING - Exception schematizing this event date: Much Ado About Nothing
Traceback (most recent call last):
  File "/Users/mcallistercs/Desktop/Github/capital-nature-ingest/events/montgomery.py", line 155, in schematize_event_date
    datetime_obj = datetime.strptime(event_date, "%a. %B %d, %Y")
  File "/Users/mcallistercs/anaconda/lib/python3.6/_strptime.py", line 565, in _strptime_datetime
    tt, fraction = _strptime(data_string, format)
  File "/Users/mcallistercs/anaconda/lib/python3.6/_strptime.py", line 362, in _strptime
    (data_string, format))
ValueError: time data 'Much Ado About Nothing' does not match format '%a. %B %d, %Y'
2019-07-30 18:27:42,898 - events.montgomery - WARNING - Exception schematizing this event time '['Much', 'Ado', 'About', 'Nothing', 'Tuesday,', 'July', '9', '|', '6:30-8:45', 'pm', '|', 'FREE', 'Brookside', 'Gardens', '–', '1800', 'Glenallan', 'Ave,', 'Whean,', 'MD', '20902']' from                         https://www.montgomeryparks.org/events/shakespeare-in-the-garden/
Traceback (most recent call last):
  File "/Users/mcallistercs/Desktop/Github/capital-nature-ingest/events/montgomery.py", line 61, in parse_event_date
    start_time = schematize_event_time(split_date[-2])
  File "/Users/mcallistercs/Desktop/Github/capital-nature-ingest/events/montgomery.py", line 169, in schematize_event_time
    datetime_obj = datetime.strptime(event_time, "%I:%M%p")
  File "/Users/mcallistercs/anaconda/lib/python3.6/_strptime.py", line 565, in _strptime_datetime
    tt, fraction = _strptime(data_string, format)
  File "/Users/mcallistercs/anaconda/lib/python3.6/_strptime.py", line 362, in _strptime
    (data_string, format))
ValueError: time data 'MD' does not match format '%I:%M%p'
2019-07-30 18:27:42,899 - events.montgomery - WARNING - Exception schematizing this event time '['Much', 'Ado', 'About', 'Nothing', 'Tuesday,', 'July', '9', '|', '6:30-8:45', 'pm', '|', 'FREE', 'Brookside', 'Gardens', '–', '1800', 'Glenallan', 'Ave,', 'Whean,', 'MD', '20902']' from                         https://www.montgomeryparks.org/events/shakespeare-in-the-garden/
Traceback (most recent call last):
  File "/Users/mcallistercs/Desktop/Github/capital-nature-ingest/events/montgomery.py", line 67, in parse_event_date
    end_time = schematize_event_time(split_date[-1])
  File "/Users/mcallistercs/Desktop/Github/capital-nature-ingest/events/montgomery.py", line 169, in schematize_event_time
    datetime_obj = datetime.strptime(event_time, "%I:%M%p")
  File "/Users/mcallistercs/anaconda/lib/python3.6/_strptime.py", line 565, in _strptime_datetime
    tt, fraction = _strptime(data_string, format)
  File "/Users/mcallistercs/anaconda/lib/python3.6/_strptime.py", line 362, in _strptime
    (data_string, format))
ValueError: time data '20902' does not match format '%I:%M%p'
```

## Possible Solution
Go checkout the event pages and see what's different about the datetimes.

## Steps to Reproduce (for bugs)
`python events/montgomery.py`

## Context
This warning is only raised on a few events, but fixing it will mean we're capturing those events (and future ones like it). It'll also declutter the logs.

**Comment by csmcallister** [comment]
Closed by 091f16a
