### ISSUE TITLE
BUG: Fairfax scraper fails when an event website lacks event times

### ISSUE THREAD

**Issue by csmcallister** [DataKind-DC/capital-nature-ingest#157]
## Expected Behavior
If a Fairfax Event is missing start/end dates/times on the event website, then we can't get all the data we need and that error should pass silently.

## Current Behavior
This error raises an exception:

```bash
ERROR: test_main (tests.fairfax_test.FairfaxTestCase)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/circleci/project/tests/fairfax_test.py", line 20, in test_main
    events = main()
  File "/home/circleci/project/events/fairfax.py", line 243, in main
    event_cost, event_description, event_venue, start_date, end_date, start_time, end_time = parse_event_website(event_website)
  File "/home/circleci/project/events/fairfax.py", line 179, in parse_event_website
    start_date, end_date, start_time, end_time = get_event_date_times(soup, event_website)
  File "/home/circleci/project/events/fairfax.py", line 47, in get_event_date_times
    start_date, end_date = get_event_dates(event_time_div_text)
  File "/home/circleci/project/events/fairfax.py", line 119, in get_event_dates
    start_date = dates[0]
IndexError: list index out of range
```

## Possible Solution
This [event](https://www.fairfaxcounty.gov/parks/huntley-meadows/catch-critter) raised the error, and it does appear that it is completely missing event time info. Because of this, we should ignore this exception but improve the logging - by including the event website - in case something similar happens again.

## Steps to Reproduce (for bugs)
See [this](https://circleci.com/gh/DataKind-DC/capital-nature-ingest/235?utm_campaign=vcs-integration-link&utm_medium=referral&utm_source=github-build-link).

Or:

```bash
python3 -m unittest tests.fairfax_test.py
```

## Context
This errors interrupts the Fairfax scrape, so fixing it is a priority.

**Comment by csmcallister** [comment]
closed by a5c58dd
