### ISSUE TITLE
BUG: ANS Event Source Scraping Error

### ISSUE THREAD

**Issue by csmcallister** [DataKind-DC/capital-nature-ingest#162]
## Expected Behavior
The ANS scraper should work! 😢 

## Current Behavior
We discovered that the scraper broke when submitting a PR for another event source.

## Possible Solution
JSON for each event can be found with this:

```python
scripts = soup.find_all('script', {'type':'application/ld+json'})
```

## Steps to Reproduce (for bugs)
Run the ANS scraper:

```python
python events/ans.py
```

And you'll see this traceback:

```
Traceback (most recent call last):
  File "/home/circleci/project/tests/ans_test.py", line 20, in test_main
    events = main()
  File "/home/circleci/project/events/ans.py", line 93, in main
    start_time = schematize_event_time(span_time.find('span', {'class': 'start'}).text)
AttributeError: 'NoneType' object has no attribute 'find'
```
Issue is likely a change in the HTML content of the website.

## Context
This is a total break for the event source, so it's pretty critical to fix it.

**Comment by csmcallister** [comment]
Closed by e0d2fdc
