### ISSUE TITLE
BUG: Eventbrite events are failing

### ISSUE THREAD

**Issue by csmcallister** [DataKind-DC/capital-nature-ingest#165]
## Expected Behavior
Eventbrite sources work.

## Current Behavior
All of the Eventbrite event sources are failing with the same error. Perhaps there was a change in their API or there's an issue with the API token.

## Steps to Reproduce (for bugs)
Run any test suite for an Eventbrite source, such as FONA, and you'll get the following traceback:

```python
Traceback (most recent call last):
  File "/Users/mcallistercs/Desktop/Github/capital-nature-ingest/tests/dc_audubon_test.py", line 20, in test_main
    events = main()
  File "/Users/mcallistercs/Desktop/Github/capital-nature-ingest/events/dc_audubon.py", line 141, in main
    dc_audubon_ingester.scrape()
  File "/Users/mcallistercs/Desktop/Github/capital-nature-ingest/events/dc_audubon.py", line 124, in scrape
    page = page.json()
  File "/Users/mcallistercs/Desktop/Github/capital-nature-ingest/env/lib/python3.6/site-packages/requests/models.py", line 896, in json
    return complexjson.loads(self.text, **kwargs)
  File "/Users/mcallistercs/anaconda/lib/python3.6/json/__init__.py", line 354, in loads
    return _default_decoder.decode(s)
  File "/Users/mcallistercs/anaconda/lib/python3.6/json/decoder.py", line 339, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/Users/mcallistercs/anaconda/lib/python3.6/json/decoder.py", line 357, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)
```

## Context
There are four event sources that depend on the eventbrite API, so fixing this is pretty urgent.

**Comment by csmcallister** [comment]
This problem appears to be a the result of an issue with their API since even console calls from their API documentation produce the same error (c.f. [this](https://www.eventbrite.com/platform/api#/reference/event-search/search-events?console=1)).

**Comment by csmcallister** [comment]
Confirmation that Eventbrite accidentally broke the `search` endpoint and is working to fix/replace it:

https://groups.google.com/forum/#!topic/eventbrite-api/-E0MG7THMsc
