### ISSUE TITLE
BUG: ANS event scraper breaks due to source html changes

### ISSUE THREAD

**Issue by csmcallister** [DataKind-DC/capital-nature-ingest#96]
## Expected Behavior
Although it's impossible to prevent a website we're scraping from changing their html, we should write code that fails gracefully, i.e. without exiting the script and losing all of the other events we've scraped from that source. In the events that something unexpected happens, like a `<p>` tag that we thought was present but that has in fact disappeared, we should include error handling and log those edge cases.

## Current Behavior
```
2019-05-07 18:21:45,455 - __main__ - CRITICAL - Exception getting events in events.ans:  'NoneType' object has no attribute 'find_all'
Traceback (most recent call last):
  File "get_events.py", line 101, in get_events
    source_events = event_source.main()
  File "/Users/mcallistercs/Desktop/Github/capital-nature-ingest/events/ans.py", line 86, in main
    event_description = get_event_description(event_website_soup)
  File "/Users/mcallistercs/Desktop/Github/capital-nature-ingest/events/ans.py", line 37, in get_event_description
    p_tags = eventon_full_description.find_all('p')
AttributeError: 'NoneType' object has no attribute 'find_all'
```

## Possible Solution
Add some logging or print statements to see which ANS event this error is occurring on and then go check out that event's page. Make the fix and then include that logging along with error handling in the solution, making sure the log message provides enough information to easily diagnose any future occurrences.

## Context
This is a pretty nasty bug as just a single event can raise the error and cause the rest of the ANS events to be lost when the script exits.

**Comment by csmcallister** [comment]
closed by 8cbd43b
