### ISSUE TITLE
BUG: VNPS event scraper fails due to source html changes

### ISSUE THREAD

**Issue by csmcallister** [DataKind-DC/capital-nature-ingest#97]
## Expected Behavior
Although it's impossible to prevent a website we're scraping from changing their html, we should write code that fails gracefully, i.e. without exiting the script and losing all of the other events we've scraped from that source. In the events that something unexpected happens, like a <p> tag that we thought was present but that has in fact disappeared, we should include error handling and log those edge cases.

## Current Behavior
```
2019-05-07 18:25:07,029 - __main__ - CRITICAL - Exception getting events in events.vnps:  too many values to unpack (expected 2)
Traceback (most recent call last):
  File "get_events.py", line 101, in get_events
    source_events = event_source.main()
  File "/Users/mcallistercs/Desktop/Github/capital-nature-ingest/events/vnps.py", line 219, in main
    date_and_time, description_and_location = row.find_all('td')
ValueError: too many values to unpack (expected 2)
```

## Possible Solution
Go checkout the VNPS events calendar page and see which `<td>` tag doesn't contain the expected two values to unpack. Make the fix and then include that logging along with error handling in the solution, making sure the log message provides enough information to easily diagnose any future occurrences.

## Context
This is a pretty nasty bug as just a single event can raise the error and cause the rest of the ANS events to be lost when the script exits.

**Comment by csmcallister** [comment]
fixed by 955b15a
