### ISSUE TITLE
BUG: DUG Network event scraper breaks due to source html changes

### ISSUE THREAD

**Issue by csmcallister** [DataKind-DC/capital-nature-ingest#98]
## Expected Behavior
Although it's impossible to prevent a website we're scraping from changing their html, we should write code that fails gracefully, i.e. without exiting the script and losing all of the other events we've scraped from that source. In the events that something unexpected happens, like a <p> tag that we thought was present but that has in fact disappeared, we should include error handling and log those edge cases.

## Current Behavior
```
2019-05-07 18:25:10,686 - __main__ - CRITICAL - Exception getting events in events.dug_network:  list index out of range
Traceback (most recent call last):
  File "get_events.py", line 101, in get_events
    source_events = event_source.main()
  File "/Users/mcallistercs/Desktop/Github/capital-nature-ingest/events/dug_network.py", line 69, in main
    events_content = json.loads(events_divs[0].string.strip())
```

## Possible Solution
Go checkout the DUG Network events calendar page and see why those `event_divs` are missing. Make the fix and then include that logging along with error handling in the solution, making sure the log message provides enough information to easily diagnose any future occurrences.

>Note: this issue also appeared in the latest master [build](https://circleci.com/gh/DataKind-DC/capital-nature-ingest/145?utm_campaign=workflow-failed&utm_medium=email&utm_source=notification) on CircleCI.

## Context
This is a pretty nasty bug as just a single event can raise the error and cause the rest of the ANS events to be lost when the script exits.

**Comment by csmcallister** [comment]
closed by 98b97ed
